### ISSUE TITLE
[ToDo] Remaining Implementation Tasks

### ISSUE THREAD

**Issue by tjjordan** [hyrise-mp-22-23/hyrise#125]
An incomplete list of open tasks for the project implementation.
Feel free to edit.

- [ ] Decide how to align our approach with the old binary caching
  - What about the copied export() functions 
- [x] Decide if the Chunks should be able to persist themselves
  - Would be better for object orientation, but Chunks are pretty dump and should stay dump
- [ ] Write unit tests for implementation
- [ ] Improve object orientation in the Segment offset calculation
  - [ ] Move size calculation to the segments, `size_bytes()`
- [ ] Decide how to deal with the base vectors of the segments
  - Make them std::optional?
